name: Update Scoreboards

on:
  push:
    branches:
      - main

jobs:
  format-code:
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v3
      - run: ./.github/tools/generate_repo_readme.py
      - uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: [Auto Commit] Update Scoreboards
