name: Update READMEs

on:
  push:
    branches:
      - main

jobs:
  update-readmes:
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v3
        with:
          ref: ${{ github.head_ref }}
          token: ${{ secrets.PAT }}

      - uses: actions/setup-python@v4
        with:
          python-version: "3.10"
          cache: "pip"

      - run: "pip install -r ./.github/tools/requirements.txt"
      - run: "./.github/tools/generate_problem_readmes.py"
      - run: "./.github/tools/generate_repo_readme.py"

      - uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: "[Auto Commit] Update README.md"
